### ISSUE TITLE
Closure logic

### ISSUE THREAD

**Issue by dcaba** [dachad/check-max-tcp-connections#13]
The current version of this program:
* tries to open as many connections as requested
* keeps the connections open unless the other end closes the connections (normally by timeout) or refuses the connections
* and, only when all connections are closed or errored, the program finishes

We should think about a better termination logic. Maybe:
* a flag stating the number of seconds we want to keep each single connection open before forcing a closure in our end
* or, maybe we can just start by: keep the program running until all connections are in the state "closed, errored or established", so there's no connections waiting to be dialed or dialing. When the program finishes, print a final report with some stats, including how long it took to reach this desired state.

In this stage, I'd bet for the second option

**Comment by chadell** [comment]
Following your suggested approach, I would change `net.Dial` to `net.DialTimeout` to put a Connection as `error` after a defined Timeout, if not I'm not sure a connection is closed eventually

**Comment by dcaba** [comment]
Nice suggestion, but this timeout only applies to "how long it will take to try to establish a connection", not "how long the connection will remain open". But I covered this in the referenced PR.

**Comment by dcaba** [comment]
(implementation idea: extra goroutine, which gets notified from the routine updating the map with connection statuses and captures signals, so it prints a nice output when finishes)

**Comment by dcaba** [comment]
(finding that may change the implementation idea: read https://blog.golang.org/pipelines . Closing the channel may be enough and prevents us sending as many closure channels as goroutines)

**Comment by dcaba** [comment]
(its a good moment to return a consistent exist status )

**Comment by dcaba** [comment]
(we should also capture signals)

**Comment by dcaba** [comment]
(dial timeout should be a flag)

**Comment by dcaba** [comment]
(move printing outside of the main go file)

**Comment by dcaba** [comment]
everything covered in https://github.com/dachad/check-max-tcp-connections/pull/20 , but metrics, that is a separate issue
