### ISSUE TITLE
Integrate codacy

### ISSUE THREAD

**Issue by dcaba** [dachad/check-max-tcp-connections#3]
https://www.codacy.com/

Easy to integrate, and quite useful.. quick win

**Comment by chadell** [comment]
Codacy doesn't support GO integration :( 
https://stackshare.io/stackups/codacy-vs-codecov
@dcaba Shall we consider Codecov as an alternative?

**Comment by dcaba** [comment]
Its not clear for me they are an alternative, but may complement each other. As you have seen, codacy still covers style checks... while i understand codecov focuses in test coverage (that is what is currently missing in codacy). So up to you, but if you did codacy, it may be enough for now :)

**Comment by chadell** [comment]
I agree, for now it's ok

**Comment by chadell** [comment]
Related PR #9

**Comment by dcaba** [comment]
Please, move the project to the organization we are now sharing:
https://www.codacy.com/organizations/dachad

**Comment by chadell** [comment]
done
