### ISSUE TITLE
Security check before execute

### ISSUE THREAD

**Issue by chadell** [dachad/check-max-tcp-connections#5]
Because it's execution could became something like a SYN flood DoS, it would be great to show what's gonna do the program before just doing it. 
Something like showing the parameters of the execution.
This behaviour could be avoided by using a -f / --force option when calling it

**Comment by chadell** [comment]
Avoid default values, explicit arguments

**Comment by dcaba** [comment]
implemented finally as "assumeyes" (to skip the confirmation)
